//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLead.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        public int LeadID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string DayPhoneNo { get; set; }
        public string EveningPhoneNo { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
